G.D Mountain Bike Shop/MountainBikeShop.Web/Models/ViewModels/MyAddsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MountainBikeShop.Web.Models.ViewModels
{
    public class MyAddsViewModel
    {
        public MyAddsViewModel(IEnumerable<BikeViewModel> myBikes=null, IEnumerable<FrameViewModel> myFrames=null, IEnumerable<ForkViewModel> myForks=null)
        {
            this.MyBikeAdds = myBikes;
            this.MyForkAdds = myForks;
            this.MyFrameAdds = myFrames;
        }

        public IEnumerable<BikeViewModel> MyBikeAdds { get; set; }

        public IEnumerable<ForkViewModel> MyForkAdds { get; set; }

        public IEnumerable<FrameViewModel> MyFrameAdds{ get; set; }

    }
}

G.D Mountain Bike Shop/MountainBikeShop.Web/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MountainBikeShop.Data.UnitOfWork;
using MountainBikeShop.Web.Models.BindingModels;
using MounrainBikeShop.Models;
using Microsoft.AspNet.Identity;
using AutoMapper;
using MountainBikeShop.Web.Models.ViewModels;
using PagedList;

namespace MountainBikeShop.Web.Controllers
{
    public class BikesController : BaseController
    {
        public BikesController(IData data) : base(data)
        {
        }

        // GET: Bikes
        public ActionResult Index()
        {
            var bikes = this.Data.MtbAdds.All().OrderBy(b => b.PostedOn);
            var mappedBikes = Mapper.Map<IEnumerable<BikeViewModel>>(bikes);
            
            return View(mappedBikes);
        }
        
        [HttpGet]
        [Authorize]
        public ActionResult NewAdd()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult NewAdd(BikeBindingModel mtb)
        {
            
            if (!this.ModelState.IsValid)
            {
                return this.View(mtb);
            }
            var bikeAdd = Mapper.Map<MountainBikeAdd>(mtb);
            
            bikeAdd.PostedOn = DateTime.Now;
            bikeAdd.UserId = this.User.Identity.GetUserId();
            this.Data.MtbAdds.Add(bikeAdd);
            this.Data.SaveChanges();
            
            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Add(int id)
        {
            var bike = this.Data.MtbAdds.All().FirstOrDefault(b => b.Id == id);
            if(bike == null)
            {
                //TODO : make error view
                return this.View("Error");
            }
            var mapperBike = Mapper.Map<BikeViewModel>(bike);
            return this.View(mapperBike);
        }

        [HttpPost]
        public PartialViewResult Search(string query)
        {
            var bikes = this.Data.MtbAdds.All().Where(m => m.Brand.Contains(query) || m.Model.Contains(query));

            var mappedBikes = Mapper.Map<IEnumerable<BikeViewModel>>(bikes);
            return this.PartialView("_Search", mappedBikes);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var bike = this.Data.MtbAdds.Find(id);
            if(bike == null)
            {
                return this.View("Error");
            }
            this.Data.MtbAdds.Remove(bike);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index", "MyAdds");
        }
    }
}

G.D Mountain Bike Shop/MountainBikeShop.Web/Controllers/ForksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MountainBikeShop.Data.UnitOfWork;
using MountainBikeShop.Web.Models.BindingModels;
using MounrainBikeShop.Models;
using Microsoft.AspNet.Identity;
using AutoMapper;
using MountainBikeShop.Web.Models.ViewModels;

namespace MountainBikeShop.Web.Controllers
{
    public class ForksController : BaseController
    {
        public ForksController(IData data) : base(data)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AllForkAdds()
        {
            var forks = this.Data.ForkAdds.All().OrderBy(m => m.PostedOn);
            var mappedForkAdds = Mapper.Map<IEnumerable<ForkViewModel>>(forks);
            return this.Json(mappedForkAdds, JsonRequestBehavior.AllowGet);
        }
 
        [Authorize]
        [HttpGet]
        public ActionResult NewAdd()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewAdd(ForkBindingModel fork)
        {
            if (!this.ModelState.IsValid)
            {
                return null;
            }
            var newFork = Mapper.Map<ForkAdd>(fork);
            
            newFork.PostedOn = DateTime.Now;
            newFork.UserId = this.User.Identity.GetUserId();
            this.Data.ForkAdds.Add(newFork);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Add(int id)
        {
            var fork = this.Data.ForkAdds.All().FirstOrDefault(b => b.Id == id);
            if (fork == null)
            {
                //TODO : make error view
                return this.View("Error");
            }
            var mappedFork = Mapper.Map<ForkViewModel>(fork);
            return this.View(mappedFork);
        }

        [HttpPost]
        public PartialViewResult Search(string query)
        {
            var forks = this.Data.ForkAdds.All().Where(m => m.Brand.Contains(query)|| m.Model.Contains(query));

            var mappedForks = Mapper.Map<IEnumerable<ForkViewModel>>(forks);
            return this.PartialView("_Search", mappedForks);
        }
    }
}

G.D Mountain Bike Shop/MountainBikeShop.Web/Controllers/FramesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MountainBikeShop.Data.UnitOfWork;
using MountainBikeShop.Web.Models.BindingModels;
using AutoMapper;
using MounrainBikeShop.Models;
using Microsoft.AspNet.Identity;
using MountainBikeShop.Web.Models.ViewModels;

namespace MountainBikeShop.Web.Controllers
{
    public class FramesController : BaseController
    {
        public FramesController(IData data) : base(data)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllFrameAdds()
        {
            var frames = this.Data.FrameAdds.All().OrderBy(m => m.PostedOn);
            var mappedFrames = Mapper.Map<IEnumerable<FrameViewModel>>(frames);
            return this.Json(mappedFrames, JsonRequestBehavior.AllowGet);
        }


        [Authorize]
        [HttpGet]
        public ActionResult NewAdd()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewAdd(FrameBindingModel frame)
        {
            if (!this.ModelState.IsValid)
            {
                return null;
            }
            var newFork = Mapper.Map<FrameAdd>(frame);

            newFork.PostedOn = DateTime.Now;
            newFork.UserId = this.User.Identity.GetUserId();
            this.Data.FrameAdds.Add(newFork);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Add(int id)
        {
            var frame = this.Data.FrameAdds.All().FirstOrDefault(b => b.Id == id);
            if (frame == null)
            {
                //TODO : make error view
                return this.View("Error");
            }
            var mappedFrame = Mapper.Map<FrameViewModel>(frame);
            return this.View(mappedFrame);
        }



        [HttpPost]
        public PartialViewResult Search(string query)
        {
            var frames = this.Data.FrameAdds.All().Where(m => m.Brand.Contains(query) || m.Model.Contains(query));

            var mappedFrames = Mapper.Map<IEnumerable<FrameViewModel>>(frames);
            return this.PartialView("_Search", mappedFrames);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var frame = this.Data.FrameAdds.Find(id);
            if (frame == null)
            {
                return this.View("Error");
            }
            this.Data.FrameAdds.Remove(frame);
            this.Data.SaveChanges();
            return this.RedirectToAction("Index", "MyAdds");
        }
    }
}

G.D Mountain Bike Shop/MountainBikeShop.Web/Controllers/MyAddsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MountainBikeShop.Data.UnitOfWork;
using Microsoft.AspNet.Identity;
using AutoMapper;
using MountainBikeShop.Web.Models.ViewModels;

namespace MountainBikeShop.Web.Controllers
{
    public class MyAddsController : BaseController
    {
        public MyAddsController(IData data) : base(data)
        {
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var loggedUserUsername = this.User.Identity.GetUserId();
            var bikes = this.Data.MtbAdds.All().Where(u=>u.UserId==loggedUserUsername).OrderByDescending(m => m.PostedOn);
            var forks = this.Data.ForkAdds.All().Where(u => u.UserId == loggedUserUsername).OrderByDescending(m => m.PostedOn);
            var frames = this.Data.FrameAdds.All().Where(u => u.UserId == loggedUserUsername).OrderByDescending(m => m.PostedOn);

            var mappedBikes = Mapper.Map<IEnumerable<BikeViewModel>>(bikes);
            var mappedForks = Mapper.Map<IEnumerable<ForkViewModel>>(forks);
            var mappedFrames = Mapper.Map<IEnumerable<FrameViewModel>>(frames);
            var myAddsViewModel = new MyAddsViewModel(mappedBikes, mappedFrames, mappedForks);
            
            return View(myAddsViewModel);
        }
    }
}

G.D Mountain Bike Shop/MountainBikeShop.Web/Views/MyAdds/Index.cshtml
@model MountainBikeShop.Web.Models.ViewModels.MyAddsViewModel
<div class="myAdds">
    <h1>My Adds</h1>
    <section>
        <h1>My bike adds</h1>
        @if (!Model.MyBikeAdds.Any())
        {
            <h1>You didn't have such adds.</h1>
        }
        @foreach (var bikeAdd in Model.MyBikeAdds)
            {
            <div class="myAdd">
                <header>
                    <h1>@bikeAdd.Brand @bikeAdd.Model</h1>
                </header>
                <section>
                    <h2>Price: @bikeAdd.Price &#36</h2>
                    
                    <p class="moreDetails">
                        @Html.ActionLink("More Details", "Add", "Bikes", new { id = bikeAdd.Id }, new { @class = "btn btn-info" })
                       
                        @Html.ActionLink("Delete", "Delete", "Bikes", new { id = bikeAdd.Id }, new { @class = "btn btn-danger" })
                    
                    </p>
                </section>
            </div>
        }
    </section>
    <section>
        <h1>My Forks adds</h1>
        @if (!Model.MyForkAdds.Any())
        {
            <h1>You didn't have such adds.</h1>
        }
        @foreach (var forkAdd in Model.MyForkAdds)
            {
            <div class="myAdd">
                <header>
                    <h1>@forkAdd.Brand @forkAdd.Model</h1>
                </header>
                <section>
                    <h2>Price: @forkAdd.Price &#36</h2>

                    <p class="moreDetails">
                        @Html.ActionLink("More Details", "Add", "Forks", new { id = forkAdd.Id }, new { @class = "btn btn-info" })
                       
                        @Html.ActionLink("Delete", "Delete", "Forks", new { id = forkAdd.Id }, new { @class = "btn btn-danger" })

                    </p>
                </section>
            </div>
        }
    </section>
    <section>
        <h1>My Frame adds</h1>
        @if (!Model.MyFrameAdds.Any())
        {
            <h1>You didn't have such adds.</h1>
        }
        @foreach (var frameAdd in Model.MyFrameAdds)
            {
            <div class="myAdd">
                <header>
                    <h1>@frameAdd.Brand @frameAdd.Model</h1>
                </header>
                <section>
                    <h2>Price: @frameAdd.Price &#36</h2>

                    <p class="moreDetails">
                        @Html.ActionLink("More Details", "Add", "Frames", new { id = frameAdd.Id }, new { @class = "btn btn-info" })
                       
                        @Html.ActionLink("Delete", "Delete", "Frames", new { id = frameAdd.Id }, new { @class = "btn btn-danger" })

                    </p>
                </section>
            </div>
        }
    </section>
</div>